# Site
name: "Kate의 집"
title: "Kate의 집"
description: "집, 인테리어, 소품을 고르고 골라서 소개해 드리는 블로그 입니다."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
url: 'https://richheadco.github.io/'
google_analytics: 'UA-203298674-1'
disqus: 'kate-house'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Kate:
    name: Kate
    display_name: Kate
    gravatar: ac61510ca8374e31e15e354e094a9702
    email: wowthemesnet@gmail.com
    web: https://richheadco.github.io/kate_house/
    twitter: 
    description: "나만의 집을 꾸미는 데 고르기 어려운 인테리어 가구나 소품을 소개해드리는 블로거입니다."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12 
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
